/**
 * FSAE Library CAN Defines
 * AutoGenerated File
 */
#ifndef CAN_H
#define CAN_H

/**
 * CAN message IDs
 */
{% loop in $ids %}
#define {$def}      {$id}
{% onEmpty %}
{% endloop %}

/**
 * Byte Positions, Bit Positions, Scalars and Offsets
 */
{% loop in $fieldDefs %}
#define {$def}      {$value}
{% onEmpty %}
{% endloop %}

#endif /* CAN_H */
